ETOSPHERES-Labs/etopay-sdk

api_types/src/api/user.rs
- Updated the api types since we do not have a clear flow yet with the (git sub tree / repo). Those were modified in the backend but we need to update the api_types also here. For now we do it manually.
=> chore: update api types

.github/workflows/ci.yml, Cargo.toml, deny.toml, sdk/bindings/android/Cargo.toml, sdk/bindings/swift/Cargo.toml, sdk/bindings/wasm/Cargo.toml, testing/Cargo.toml, tools/jnigen-build/Cargo.toml, tools/jnigen-common/Cargo.toml, tools/jnigen-integration-test/Cargo.toml, tools/jnigen-macro/Cargo.toml
This runs `cargo-deny` in the CI. It checks the licenses of all dependencies to make sure they do not validate our use. Also checks against the RUSTSEC security advisory database (same as `cargo audit`) and 
- Add cargo deny config file with a list of accepted licenses (reviewers please double-check if reasonable)
- Add CI job that runs cargo deny.
- Mark all crates except `sdk` and `api_types` as non-publishable since they are only used internally to generate bindings and artifacts.
=> chore(ci): add `cargo deny` ci and config

.github/workflows/manual-trigger.yml
=> ci: publish wasm to npm

.env.example, sdk/tests/rt_transaction.rs, sdk/tests/utils/mod.rs, testing/src/testuser.rs
We need to run the regression tests (especially the send compliment) on the iota mainnet since the testnet is not supported on Viviswap.
- The send compliment regression tests in run with user `HANS34`. Therefore we update his mnemonic, but we put is as an env variable to hide it.
- Update the sdk config to use the iota mainnet url
=> refarctor: change sdk config and update with a mainnet wallet

sdk/bindings/android/tests/build.gradle, sdk/bindings/swift/examples/run_all_examples.sh, sdk/bindings/wasm/examples/run_all_examples.sh, sdk/examples/run_all_examples.sh, sdk/tests/rt_transaction.rs
We decided to temporarily disable the `send compliment` tests and examples.
- Ignore rt.
- Comment out examples.
=> chore: comment out send compliment tests and examples

sdk/README.md, sdk/docs/Installing the SDK/Installation.md, sdk/docs/Installing the SDK/Rust.md
Adding install instruction for rust lang.
- Change 1
- Change 2
=> Add install instructions for rust

.cargo/config.toml, .devcontainer/docker-compose.yml
Just update the tag, remove `clang` and `lld` version specifier 💯 
Note: the tag does not (yet) exist, this is just to make the transition possible.
=> chore: update to new devcontainer tag

sdk/bindings/android/Makefile, sdk/bindings/android/build.rs, sdk/bindings/swift/Makefile, sdk/bindings/swift/examples/Makefile, sdk/docs/Choosing Cawaena/Licensing.md, sdk/mkdocs.yml
Fix the docs and set the right company name
=> chore(docs): change company name

.github/workflows/ci.yml, .github/workflows/manual-trigger.yml, Cargo.lock, Makefile, sdk/bindings/wasm/Cargo.toml, sdk/bindings/wasm/examples/webapp/examples/01-create_new_user.js, sdk/bindings/wasm/examples/webapp/examples/02-onboard_user_via_postident.js, sdk/bindings/wasm/examples/webapp/examples/03-create_new_wallet.js, sdk/bindings/wasm/examples/webapp/examples/04-migrate_wallet_from_mnemonic.js, sdk/bindings/wasm/examples/webapp/examples/05-migrate_wallet_from_backup.js, sdk/bindings/wasm/examples/webapp/examples/06-generate_new_address.js, sdk/bindings/wasm/examples/webapp/examples/07-get_balance.js, sdk/bindings/wasm/examples/webapp/examples/08-create_purchase_request.js, sdk/bindings/wasm/examples/webapp/examples/09-onboard_user_via_viviswap.js, sdk/bindings/wasm/examples/webapp/examples/10-verify_pin.js, sdk/bindings/wasm/examples/webapp/examples/11-reset_pin.js, sdk/bindings/wasm/examples/webapp/examples/12-change_password.js, sdk/bindings/wasm/examples/webapp/examples/13-send_amount.js, sdk/bindings/wasm/examples/webapp/examples/14-get_exchange_rate.js, sdk/bindings/wasm/examples/webapp/examples/15-claim_output.js, sdk/bindings/wasm/examples/webapp/examples/16-get_tx_list.js, sdk/bindings/wasm/examples/webapp/examples/17-create_customer.js, sdk/bindings/wasm/examples/webapp/examples/18-delete_user.js, sdk/bindings/wasm/examples/webapp/examples/19-get_wallet_tx_list.js, sdk/bindings/wasm/examples/webapp/examples/20-send_compliment.js, sdk/bindings/wasm/examples/webapp/examples/util.js, sdk/bindings/wasm/examples/webapp/package.json, sdk/bindings/wasm/package.json
~~It was wrong, and now it should be correct 💯~~
Well it seems there were more issues. Now it should be fixed and everything works!
See https://www.npmjs.com/package/@cawaena/cawaena-sdk-wasm
And the job: https://github.com/ETOSPHERES-Labs/cawaena-sdk/actions/runs/13697305900
Also went ahead and renamed the crate to `cawaena` from `cryptpay` (hence all changes in examples) 👍 
=> fix(ci): wasm npm publish job

sdk/bindings/wasm/examples/run_all_examples.sh
Fixes the amazing error thrown by `node`:
```
------------------------------ Running example: 05-migrate_wallet_from_backup -----------------------------------------------------------
node:internal/modules/cjs/loader:1408
throw err;
^
Error: Cannot find module './05-migrate_wallet_from_backup'
Require stack:
- /workspaces/cryptpay.rs/sdk/sdk/bindings/wasm/examples/imaginaryUncacheableRequireResolveScript
at Function._resolveFilename (node:internal/modules/cjs/loader:1405:15)
at Function.resolve (node:internal/modules/helpers:145:19)
at requireResolveNonCached (/workspaces/cryptpay.rs/sdk/sdk/bindings/wasm/node_modules/.pnpm/ts-node@10.9.2_@types+node@18.19.76_typescript@4.9.5/node_modules/ts-node/dist/bin.js:549:16)
at getProjectSearchDir …
```
=> fix: add missing `.ts` extension to `run_all_examples.sh` script

Cargo.lock
- Fixes an error by `cargo audit` with `ring`   (https://rustsec.org/advisories/RUSTSEC-2025-0009)
- Updates `anymap3` to avoid warning about incompatibilities with future rust versions.
=> chore(deps): bump `ring` to `v0.17.13` and `anymap3` to `v1.0.1`

.github/workflows/ci.yml, .github/workflows/deploy-android.yml, .github/workflows/deploy-swift.yml, .github/workflows/deploy-wasm.yml, .github/workflows/deploy.yml, Cargo.lock, Makefile, sdk/bindings/android/.gitignore, sdk/bindings/android/Cargo.toml, sdk/bindings/android/Makefile, sdk/bindings/android/build.rs, sdk/bindings/android/pom.xml, sdk/bindings/android/settings.xml, sdk/bindings/android/tests/build.gradle
TLDR: we will now publish SNAPSHOT versions automatically to Maven Central on every PR merge 💯 
- Rename the generated lib from `walletsdk_jni` to `walletsdk`. Removes need for renaming generated `.so` files, and also simplifies the `gradle.build` file for running the tests and examples.
- Rename the android binding crate from `cryptpay-sdk-jni` to `cawaena-sdk-jni`.
- Remove the auto-generated `pom.xml` and `settings.xml` files in favor of comited easily editable files.
- Auto-package all native libs into a separate `.jar` file using the `maven-assembly-plugin`.
- Update the job to deploy using `mvn deploy` instead of `mvn deploy:file`. This lets maven do the packaging, compilation and signing (although not yet enabled, but needed for publishing non-SNAPSHOT versions) before …
=> chore(ci): publish to maven central

sdk/bindings/android/src/lib.rs, sdk/bindings/android/tests/src/test/java/com/cawaena/SdkUnitTest.java, sdk/bindings/swift/src/ffi_functions.rs, sdk/bindings/wasm/src/lib.rs, sdk/examples/utils.rs, sdk/src/core/config.rs, sdk/src/core/core_testing_utils.rs, sdk/src/core/exchange.rs, sdk/src/core/mod.rs, sdk/src/core/transaction.rs, sdk/src/core/viviswap/swap.rs, sdk/src/core/wallet.rs, sdk/tests/utils/mod.rs
ZD0006-571
- moved code to `src/core`
- changed the type of `Networks` in `Sdk` from `Option<Vector<Network>>` to `Vector<Network>`
- updated functions in bindings
- now `set_network` no longer queries the backend for the network list, `get_network` does it instead
=> Update the `getNetworks` function in the bindings

Cargo.lock, deny.toml
- Update config to match our current state. Allow some new unmaintained crates, sources from ETOGRUPPE org and remove "OpenSSL" license since the latest `ring` version has clarified its license 💯 
- Update `env_logger` to `v0.11.7` to remove dependency on unmaintained crate `humantime`.
=> chore: update `cargo-deny` config and `env_logger` to `v0.11.7`

.github/workflows/ci.yml, .github/workflows/deploy-wasm.yml
The were publishing the wasm bindings for web target. But then we could not create a quickstart project for typescript. Therefore, we need to deploy for the nodejs target.
- Update the deploy script to use the nodejs target.
=> publish for nodejs target

sdk/docs/SDK Configuration/Configuration.md, sdk/src/core/config.rs
- Rename log file from `cryptpay_sdk.log` to `etopay_sdk.log`.
changes related also to: https://gitlab.inovel.de/zd0006/cryptpay.rs/-/merge_requests/468
=> chore: rename sdk log file

Cargo.lock, sdk/Cargo.toml, sdk/bindings/android/src/lib.rs, sdk/bindings/android/tests/src/main/java/com/cawaena/examples/SendAmount13.java, sdk/bindings/swift/examples/Sources/13_send_amount/main.swift, sdk/bindings/swift/src/ffi_functions.rs, sdk/bindings/swift/src/lib.rs, sdk/bindings/wasm/examples/13-send_amount.ts, sdk/bindings/wasm/examples/webapp/examples/13-send_amount.js, sdk/bindings/wasm/src/lib.rs, sdk/examples/13_send_amount.rs, sdk/src/abi/erc20.json, sdk/src/core/transaction.rs, sdk/src/core/wallet.rs, sdk/src/types/networks.rs, sdk/src/wallet/error.rs, sdk/src/wallet/wallet_manager.rs, sdk/src/wallet/wallet_user_eth.rs
We want to support getting the balance and transferring ERC20 tokens on EVM compatible networks 💯 
- Add a variant `NetworkType::EvmErc20` which includes the contract address. 
- Add `WalletImplEthErc20` and implement `WalletUser` for it. It wraps a `WalletImplEth` and uses the same provider to call the smart contract 🔥 
- Make the `send_amount` function return the transaction id upon success 🌵 
=> feat(wallet): support ERC20 Tokens on EVM

.github/workflows/github-pages.yml
=> chore: rename public docs url

Cargo.lock
=> chore(deps): update RustySecrets to latest version with updated `rand` dep

testing/src/testuser.rs
=> chore: change email for test users

.github/workflows/deploy-wasm.yml, .github/workflows/github-pages.yml
We might as well build the docs on the public runners 💯 
Also changed the scope to build for `@etospheres` instead of `@etopay` 👍 
=> chore(ci): build docs on public runner

.github/pull_request_template.md, docs/docs/SDK Configuration/Configuration.md, docs/docs/SDK Examples/Examples.md, docs/mkdocs.yml, sdk/examples/utils.rs
The examples were no longer included after moving the docs in #94 . This is now fixed 💯 
Also updated the config section of the public docs and removed the (uneccessary PR template title)
=> fix(docs): fix inclusion of examples and update config section

Cargo.toml, sdk/Cargo.toml, sdk/bindings/wasm/Cargo.toml
Adds keywords to the entire workspace which is then inherited by the wasm binding crate and copied over to the `package.json` by `wasm-pack` (tested).
Please add more keywords via suggestions! 🔥 
=> chore: add keywords

.github/workflows/deploy-swift.yml
Again inspired by the CI in `lapce`: https://github.com/lapce/lapce/blob/master/.github/workflows/release.yml
- Run workflow when tag is pushed, take tag name as tag name of release to create in swift bindings repo.
- Allow to run workflow manually and specify a tag name.
Successful run of workflow with a manually provided tag: https://github.com/ETOSPHERES-Labs/etopay-sdk/actions/runs/14083765994/job/39443297905
Release created in swift bindings: https://github.com/ETOSPHERES-Labs/etopay-sdk-swift/releases/tag/v0.0.1
=> ci(swift): release swift bindings to tag on tag creation

bindings/android/pom.xml
Path was wrong after moving the bindings. Now fixed!
=> fix(java): fix path in pom.xml

docs/docs/SDK Modules/Managing wallet.md
Updated the description for managing wallet
- Removed IOTA related changes
- Removed deprecated ASCII art
=> docs: updated managing wallet

Cargo.lock, sdk/Cargo.toml
Combines #118  and #120 into one and updates all the `alloy` crates at the same time :rocket:
=> chore(deps): bump `alloy` from `v0.12.6` to `v0.13`

bindings/swift/src/ffi_functions.rs, bindings/swift/src/lib.rs, bindings/swift/src/type_conversion.rs, bindings/wasm/src/types.rs, sdk/src/core/viviswap/kyc.rs
Add the rest of the fields to the `Network` struct for swift and wasm bindings. This should allow users to correctly list and select networks! 💯 
=> feat(bindings): add network struct fields

docs/docs/Choosing ETOPay/Licensing.md, docs/docs/Dashboard/Dashboard.md, docs/docs/SDK Modules/Managing wallet.md, docs/docs/SDK Reference/SDK API Reference.md, sdk/src/core/viviswap/kyc.rs
- Update the Wallet management chapter to include information about SSS, remove stuff that is no longer valid and add links to API reference. Replaced code snippets with links to examples 💯 
- fix some links
- Fix Licensing chapter.
- Strip some trailing whitespace.
=> docs: update wallet management docs

CONTRIBUTING.md, README.md
=> chore(docs): add badges and links to CoC and Contribution Guidelines

api_types/src/api/generic.rs
1 small change to remove the kyc service hash from the struct that stores them.
Backend changes: https://gitlab.inovel.de/zd0006/cryptpay.rs/-/merge_requests/526
=> refactor: remove kyc from hello endpoint

docs/mkdocs.yml
=> chore(docs): update discord link

.github/workflows/github-pages.yml, docs/mkdocs.yml, docs/overrides/main.html
Version the docs using `mike` 💯 
- Version docs using `mike`: on push to main we deploy as "devel" and whenever the workflow is run manually or when a tag is created it will create the corresponding version and tag it with the alias "latest". "latest" is set as the default version to show (manually locally one-time setup using `mike set-default latest --allow-undefined`).
~~TODO: if this is accepted, I suggest we wipe the entire `gh-pages` branch clean and start from the beginning with v0.14.1 being the first version. This is because `mike` lays out the docs differently and the existing files could interfere with it working correctly. Either way no information will be lost 🚀~~
Edit: I renamed the existing `gh-pages` branch to …
=> chore(docs): version docs using `mike`

api_types/src/api/generic.rs
Simplify API by returning a single version string from the health endpoint 🚀 
=> feat(api): return single version number from health endpoint

docs/overrides/main.html
Sadly also had to get rid of the "fixed-to-background" effect. Now the image scrolls with the rest of the page. But IMO this is still better than before! 
=> fix(docs): improve hero background image for small screens

.github/workflows/github-pages.yml
Fixes some issues with the docs not being published correctly on tag push.
- Update the regex to make sure the github-pages workflow is triggered when a tag is pushed (now uses same tag as the `deploy-swift` workflow)
- Add flag to `mike deploy` to allow updating the `latest` alias to the newly deployed version.
=> fix(ci): change tag push regex, fix `mike` deploy command

docs/mkdocs.yml, docs/overrides/partials/integrations/analytics/custom.html
=> feature: add analytics to docs

docs/docs/javascripts/consent.js, docs/mkdocs.yml, docs/overrides/partials/integrations/analytics/custom.html
- Allow to Manage cookie consent
=> feat: allow to disable cookie consent

docs/docs/SDK Modules/KYC Onboarding.md, docs/docs/SDK Modules/Transactions_Swaps_Purchases.md, docs/docs/SDK Reference/SDK API Reference.md
Replace the left-over mentions of viviswap with the ETOSPHERES Exchange 💯 
Left is only actual code: names of methods and types (which we can also rename I guess since it is a massive breaking change) 🤔 
=> chore(docs): replace viviswap with Exchange

docs/mkdocs.yml, docs/overrides/partials/integrations/analytics/custom.html
- Correctly report page views using the `location$` signal 💯 (before only "real" page reloads were counted and not internal client-level navigation)
- Add link in footer to update cookie settings 🌵 
- Add feedback form + logic to report these as events to Matomo. Note: this will only report feedback if the user has consented to analytics... Is this the intended behavior?
=> feat(docs): add feedback reporting

docs/overrides/main.html
updated legal links since the old ones are now invalid
Updated link to privacy policy and imprint
=> doc: :memo: updated legal links

Cargo.lock, Cargo.toml
Release of v0.15.0 for the SDK
- Updated legal and docs
- Added basic functionalities for IOTA rebased
=> feat: 🚀  release v0.15

.github/dependabot.yml, Cargo.lock
Closes #212 #211 #209 #208
Adds directive to dependabot to group updates to all `alloy*` crates. Let's see if it works 💯 
=> chore(deps): update `alloy` crates to `v1.0.9`

bindings/android/tests/build.gradle, bindings/android/tests/src/main/java/com/etospheres/etopay/examples/SendCompliment20.java, bindings/swift/examples/Package.swift, bindings/swift/examples/Sources/20_send_compliment/main.swift, bindings/swift/examples/Sources/utils/utils.swift, bindings/swift/examples/run_all_examples.sh, bindings/wasm/examples/20-send_compliment.ts, bindings/wasm/examples/run_all_examples.sh, docs/docs/SDK Examples/Examples.md, sdk/examples/20_send_compliment.rs, sdk/examples/run_all_examples.sh
Enables the examples 8 and 20 for creating purchase requests 💯 
Lower the amount to `0.1` so that the funds don't run out too fast 🌵 
=> feat: enable examples for purchase requests

sdk/tests/rt_transaction.rs, sdk/tests/rt_wallet.rs, sdk/tests/utils/mod.rs, testing/src/keycloak.rs
=> fix: fix sdk rt

crates/etopay-wallet/Cargo.toml
=> chore: add description for etopay-wallet crate
