.cargo/config.toml, .github/workflows/ci.yml, Cargo.toml
We are currently using our self-hosted `dell` runner to run all jobs. For some reason, the runner does not pick jobs to run in parallell and thus the CI takes forever. And since the repo is now public, we might as well use the provided github-hosted runners, especially for jobs that are not that heavy.
- Change all CI jobs to use the public runners, except for `build-sdk-android` and `build-sdk-swift` which still run on `dell` using our custom image. We can consider changing this in the future.
- Breakup the `lint`  job into it's separate components.
Please provide any comments or points of consideration for the reviewers, such as specific areas of focus, potential edge …
=> chore(ci): replace custom image with stock runner image for simple jobs

Cargo.lock, Cargo.toml, sdk/Cargo.toml, sdk/bindings/android/Cargo.toml
Compiling a vendored `openssl` version takes a long time. On the other hand, there is a perfectly viable alternative: `rustls` that we can use for TLS instead. This also fixes the cargo audit error for a RUSTSEC by removing affected dependency.
- Change feature flags to remove `openssl` and use `rustls` instead.
=> chore(deps): use `rustls` instead of `openssl`

Cargo.lock, sdk/bindings/wasm/Cargo.toml
Running the wasm examples in node, we get an error "Crypto API not available". After some investigation this was found to be caused by an upgrade of `web-sys` and `js-sys` to `v.0.3.75` (#4 ) . Thus these deps have been pinned / held back to make this work again. Possibly we need to do a minimum reproduction of the error and open an issue upstream, but this does the job for now 🚀 
- Pin `web-sys` and `js-sys` to `v0.3.74`
=> chore(deps): pin web-sys and js-sys to `v0.3.74` to fix issue with Crypto API

.github/workflows/ci.yml, .github/workflows/deploy.yml, sdk/bindings/swift/Makefile
This changes the job that builds the swift bindings bundle to run on the hosted macos runners. It also adds a new CI workflow that runs only on push to main (eg. when merging a PR). That way we now have:
- all pushes build wasm bindings and swift and android bindings for native platform only.
- Building the xcframework and bundling the java jar (compiled for four different targets) is now performed only on pushes to main.
Less waste and faster CI, and we still build and test all bindings on each push to a feature branch (we just do not build for all platforms all the time) 🚀 
Please provide any comments or points of consideration for the reviewers, such as specific areas of focus, potential edge cases, or context that would aid …
=> chore(ci): use hosted mac runner for building swift bindings, bundle only on push to main

.github/workflows/ci.yml, .github/workflows/deploy.yml
Well, since the two pipelines had the same key for the concurrency, the deploy pipeline got canceled. This PR fixes that by introducing unique keys 💯 
=> fix: change pipeline concurrency to avoid jobs canceling each other

.config/nextest.toml
Nextest released a new version that contains a "fix" that outputs an error when a filter for a test group assignment does not match anything. This PR fixes that by removing the unused filter 💯 
Release Notes: https://github.com/nextest-rs/nextest/releases/tag/cargo-nextest-0.9.92
=> fix(ci): remove unused nextest group assignment

sdk/src/wallet/wallet_user.rs, sdk/tests/rt_transaction.rs, sdk/tests/utils/mod.rs
Previously we updated the sdk to run all regression tests on the iota mainnet. This affected them and started to fail. We need to revert this and run only the send compliment test on the iota mainnet. The rest of the tests should run on the iota testnet. 
We also need to reduce the amount we send since we have only 3 IOTAs on the mainnet. 
- Updated the send complement regression test to send a smaller amount of `0.1` so we don't run out of IOTA tokens. But this converts to `0.22` amount. Check it out in the [IOTA Tangle Explorer](https://explorer.iota.org/mainnet/addr/iota1qrh09fqsmen6vdtumzu7szsj5nrectcfkzvxye4k3rpzxupynmhpvf5zpsn).
- Now I config sdk manually for the send compliment example to run it on the iota mainnet.  …
=> send smaller amount

Cargo.toml, sdk/Cargo.toml
This will make `rust-analyzer` completely happy again by adding a dummy feature 💯 That way the `server` feature exists in all linked projects.
Also removed the allow of `deprecated` warning, we should not use deprecated stuff!
=> fix: add dummy feature to make rust-analyzer happy, do not allow deprecated

.github/workflows/deploy-android.yml, .github/workflows/deploy-swift.yml, sdk/bindings/android/pom.xml
Well it turns out that maven does not really work well when specifying env variable as the version in `pom.xml`. The result is:
- Package is published with the correct version to Maven Central
- But the published `pom.xml` _still has_ the `${env.PUBLISH_VERSION}` as `version` 🤯 
So instead we just do it the real way and use `sed` to replace the version in the file directly 🤞 
(Also made it possible to trigger these jobs manually, makes it easier to test them out 💯 )
(And changed some of the packaging options to make it easier to extract and use the native `.so` files)
Please provide any comments or points of consideration for the reviewers, such as specific areas of focus, potential edge cases, or context that would aid the …
=> fic(ci): use explicit replacement instead of env var for pom.xml version

Cargo.lock
I replaced `protobuf` with `prost` in `rusty_secrets`. See:
- https://github.com/ETO-GRUPPE-TECHNOLOGIES-GmbH/RustySecrets/pull/5
- https://github.com/ETO-GRUPPE-TECHNOLOGIES-GmbH/merkle.rs/commit/09fdcece8e8b3fba910c2330652e078aaaaa1b29 
This is the result of running `cargo update rusty_secrets`, `protobuf` is now completely removed from the `Cargo.lock` file! 💯 
=> chore: update rusty_secrets to latest version

sdk/examples/13_send_amount.rs, sdk/src/core/transaction.rs, sdk/src/wallet/wallet_user.rs, sdk/src/wallet/wallet_user_eth.rs
- Introduce type `TransactionIntent` to wrap all inputs related to performing a transaction. This struct is used as input for both `WalletUser::send_amount` and `WalletUser::estimate_gas_cost`. 
- Refactor EVM wallet impl to simplify and reuse logic across native and ERC20 transactions for both sending and gas estimation 💯 
- Simplify `WalletUser` trait by removing `send_transaction` (only used by Stardust wallet). We now always use `send_amount` and provide a relevant `TransactionIntent` 🔥 
- Add function `estimate_gas` to `Sdk` which can be used to estimate the gas for a transaction. 
> Note: I have _not_ added any bindings as it felt like that might change anyways as …
=> feat(wallet): unify gas estimation and simplify `WalletUser` trait

sdk/src/wallet/wallet_user_eth.rs
Generated addresses were not treated as valid in the backend. This was because we were using `to_lowercase()` on the generated address. However, the casing actually has a purpose: [it is a checksum](https://docs.alchemy.com/docs/how-to-handle-checksum-addresses) (which I was obviously unaware of when I implemented this in #76 ). And since removing the casing breaks the checksum, the backend (correctly!) treated the address as invalid 💯  
The fix is simple: remove the call to `to_lowercase` (and update the unit tests to deal with it themselves) 🚀 
=> fix(eth): remove `to_lowercase` when getting address to keep ETH address checksum valid

.github/workflows/deploy-swift.yml
We wanted to push the Swift XCFramework to GitHub job artifacts, but turns out you need to be logged into GitHub to access those (which XCode is not...). So here is my attempt at (re)creating a nightly release in https://github.com/ETOSPHERES-Labs/etopay-sdk-swift/release and upload the artifacts there. After much trial and error it actually works! 💯 
Inspired by the workflow that creates nightly releases in https://github.com/lapce/lapce/releases
=> feat(ci): create release for swift

Cargo.lock, sdk/Cargo.toml
Fix for version of `deranged` crate that got released while not being completely SemVer compatible...
Without this our dependents get the `0.4.1` version which makes `iota-sdk` not compile.
See: https://github.com/jhpratt/deranged/issues/18
=> fix(dep): lock version of `deranged` to `v0.4.0`

Cargo.lock, api_types/Cargo.toml, api_types/src/api/decimal.rs, api_types/src/api/mod.rs, api_types/src/api/transactions/create.rs, api_types/src/api/transactions/details.rs, api_types/src/api/viviswap/contract.rs, api_types/src/api/viviswap/course.rs, sdk/src/backend/transactions.rs, sdk/src/backend/viviswap.rs, sdk/src/core/exchange.rs, sdk/src/core/transaction.rs, sdk/src/testing_utils.rs, sdk/src/types/currencies.rs, sdk/src/types/transactions.rs
The default deserialization from `String` provided by `rust_decimal::Decimal` implicitly truncate/round the input if it does not fit within the number of bits. This means that a value of `10000000000000000000000000000.000000000000000001` would not cause an error, but rather be interpreted as `` which is not ideal.
To fix this we introduce `api_types::Decimal` that explicitly uses the `rust_decimal::Decimal::from_str_exact` function that returns an error if there are issues with Overflow / Underflow.
=> feat(api): introduce `Decimal` in `api_types`

sdk/src/wallet/wallet_manager.rs, sdk/src/wallet/wallet_user_eth.rs
We now use the `decimals` from the selected network in the EVM / ERC20 `WalletUser` implementations. Also added more unit testing around the conversion to/from `U256` and `CryptoAmount` 🚀 
Tested with USDC testnet network and I am able to send `2.0` USDC to myself and it will correctly send the amount, as well as fetch the transaction details correctly 💯 
=> feat(evm): use network `decimals` in EVM `WalletUser` impls

bindings/android/tests/build.gradle, bindings/wasm/Makefile, sdk/Makefile
- Fix wrong path for java examples to find the native library.
- Move makefile command into WASM bindings where it belongs.
=> fix: java library path and move Makefile for WASM examples

Cargo.lock, deny.toml
- Update `tokio` to fix [RUSTSEC-2025-0023](https://rustsec.org/advisories/RUSTSEC-2025-0023).
- Remove unencountered license in `deny.toml` config.
=> chore(deps): bump `tokio` to `v1.44.2` to fix audit warning

sdk/src/core/wallet.rs, sdk/src/testing_utils.rs
- transactions are now filtered using the active network (its network_key)
- if a transaction has a status `Confirmed`, we don't fetch it from the crypto network for synchronization (nothing will change in it anyway)
- Change 1
- Change 2
=> filtering using network_key

sdk/src/core/wallet.rs
We were always pushing the address, even if purchases are not supported by the network. This caused an error since the backend returns 500 Internal Server error for this. Changed so that we only try to push it whenever `can_do_purchases` is true for the network 💯 
=> fix: do not push address if purchases are not supported

sdk/src/wallet/rebased/rpc/coin.rs, sdk/src/wallet/wallet_rebased.rs
> This builds on #156 
Whenever we perform a transaction on IOTA Rebased, we currently need to split a coin object and send it away. This means that you can easily end up owning multiple coin objects which together have a high balance, but each separately is not enough to cover your intended transaction.
To fix that, this PR adds logic that will merge multiple existing coins into the `GasCoin` before performing the split 💯 
=> feat(iota): consolidate coins

bindings/android/src/lib.rs, sdk/src/core/config.rs, sdk/src/core/mod.rs, sdk/src/logger.rs, sdk/src/testing_utils.rs, sdk/src/wallet/share.rs, sdk/src/wallet/wallet_evm.rs, sdk/src/wallet/wallet_rebased.rs, sdk/src/wallet/wallet_stardust.rs
I've added annotations to suppress Clippy warnings:
- The first warning was about the potentially large size of the `Err` variant ([clippy::result\_large\_err](https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err)). We can safely ignore this for now, as the error size isn't a concern in our current context.
- The second warning was related to the placement of the `SAFETY:` comment for an `unsafe` block. I've adjusted the comment to align with Clippy's expectations.
=> fix: allow large error size, change unsafe annotation placement

Cargo.lock, Cargo.toml, crates/etopay-wallet/Cargo.toml, crates/etopay-wallet/src/rebased/crypto/ed25519.rs, sdk/src/wallet/share.rs, sdk/src/wallet/wallet_manager.rs
This makes the core functionality (except for storing kdbx files) work under `node` 💯 
- In places where possible, directly inject the random bytes (eg. entropy) instead of letting each library use their own (old) version of the `rand` crate which does not play nice with `node` at the moment.
- Remove the need to directly depend on the old version of `rand` 💯 
Note: not all use of the old version is fixed. The backup generation using the `kdbx` crate will continue to not work under `node`.
=> fix: use `rand` `v0.9` whenever possible

bindings/wasm/examples/06-generate_new_address.ts, bindings/wasm/src/lib.rs, crates/etopay-wallet/src/wallet.rs, crates/etopay-wallet/src/wallet_evm.rs, crates/etopay-wallet/src/wallet_rebased.rs, sdk/src/core/core_testing_utils.rs, sdk/src/core/exchange.rs, sdk/src/core/mod.rs, sdk/src/core/postident.rs, sdk/src/core/share.rs, sdk/src/core/transaction.rs, sdk/src/core/user.rs, sdk/src/core/viviswap/swap.rs, sdk/src/core/wallet.rs, sdk/src/testing_utils.rs, sdk/src/types/users.rs, sdk/src/wallet/wallet_manager.rs
We need to support having multiple accounts and addresses with the same mnemonic :rocket:
- Introduce `MnemonicDerivationOption` struct with the `account` and `index` numbers.
- Use the `account` and `index` numbers in the key derivation for both EVM and IOTA Rebased.
- Update tests.
- Add binding for WASM (`setWalletAccount(account,index)`) and add example usage in `generate_new_address` 🔥 
=> feat: add support for specifying wallet derivation account and index values

crates/etopay-wallet/src/lib.rs, crates/etopay-wallet/src/rebased/rpc/indexer.rs, crates/etopay-wallet/src/rebased/rpc/mod.rs, crates/etopay-wallet/src/wallet.rs, crates/etopay-wallet/src/wallet_evm.rs, crates/etopay-wallet/src/wallet_rebased.rs, crates/etopay-wallet/src/wallet_tx_sort.rs, sdk/examples/19_get_wallet_tx_list.rs, sdk/src/core/wallet.rs
We want to automatically discover the incoming and outgoing transactions for each address, which we can do using an extended RPC api for the IOTA Rebased nodes 💯 
- Add RPC call to list transactions based on to / from addresses.
- Add logic to call the `WalletUser::get_wallet_tx_list` function (which now returns a vector of transaction hashes) and incorporate this information directly in the local list of transactions.
- sort the transaction list based on timestamp (we will need to store the date as some numeric, eg. UTC, for that to work)
Please provide any comments or points of consideration for the reviewers, such as specific areas of focus, potential edge cases, or …
=> feat: fetch transaction list from IOTA Rebased node

bindings/wasm/examples/19-get_wallet_tx_list.ts, bindings/wasm/src/types.rs
The latest changes caused an error:
```
console.log("Wallet transactions list: " + JSON.stringify(transactions));
^
TypeError: JSON.stringify cannot serialize BigInt.
```
This pull request is to fix wasm `19-get_wallet_tx_list.ts` example.
We chose to use a callback with `JSON.stringify` to fix the problem.
=> fix: JSON.stringify BigInt error in wasm example 19-get_wallet_tx_list
